### ISSUE TITLE
Enumerating over Single Browser - Error

### ISSUE THREAD

**Issue by chrisgioia64** [chrisgioia64/ecommerce-automation#9]
On commit [run two versions of testng file -- dev/qa](https://github.com/chrisgioia64/ecommerce-automation/commit/19b34c6844d8b34168c4ed4a77d524bc9a668896),

I am running the QA version of the tests via:
`mvn test -Denv_file="qa.properties" -Pqa`

I get the following error when trying to create the data provider for the brands product test:

```
[Utils] [ERROR] [Error] java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at ecommerce.base.CrossBrowserUtils.enumerate(CrossBrowserUtils.java:11)
        at ecommerce.base.CrossBrowserUtils.enumerateDefaultBrowser(CrossBrowserUtils.java:27)
        at ecommerce.tests.ProductTest.getAllBrandsOverBrowsers(ProductTest.java:138)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

```

**Comment by chrisgioia64** [comment]
going to close.
